# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /api

# spring相关配置
spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379

  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_mysql_base
    username: root
    password: 123456

  # JPA 配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  # 启用时初始化数据
  sql:
    init:
      mode: never # always