spring:
  datasource:
    url: jdbc:h2:mem:quartz-db
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

  sql:
    init:
      mode: always

  # H2 配置
  h2:
    console:
      enabled: true
      path: /h2-console # H2控制台访问路径

  # quartz 配置
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.springframework.scheduling.quartz.LocalDataSourceJobStore  # springboot>2.5.6需调整（错误版本：org.quartz.impl.jdbcjobstore.JobStoreTX）
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 5
