

spring:
  # H2 数据库配置
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:db_noob_demo
    username: sa
    password:
  # JPA 配置
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # H2 配置
  h2:
    console:
      enabled: true