# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /api

# spring相关配置
spring:
  profiles:
    active: dev
  # jackson 配置
  jackson:
    serialization:
      indent-output: true # 美化JSON输出
    default-property-inclusion: non_null # 不序列化null值

# log 配置
logging:
  level:
    root: info
    com.noob.base: debug # com.noob.base 目录下为debug级别
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

